# pywb config file
# ========================================
#

collections:
    all: $all
    $root:
        index_group:
          src1: ./collections/sample_archive/cdx1/
          src2: ./collections/sample_archive/cdx2/
        archive_paths: ./collections/sample_archive/archive/


# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true


# Enable the CDX api
enable_cdx_api: true

continuity:
  default_redirect_page: cnf.html?url=

hooks:
   pre:
      - take_down_hook
   post:
      - take_down_hook

